### ISSUE TITLE
チケットUX改善

### ISSUE THREAD

**Issue by 10mocy** [sockbase/Sockbase#122]
- エラー表示するようにする
  - [x] チケット申し込み画面
  - [x] チケット割り当て画面
- 郵便番号入力時の自動入力が微妙
  - 3桁目入力終わりか、4桁目入力開始時にハイフンを入れるようにする
- デザイン周り
  - [x] スクショ防止でもQR出てる画面で下の方がチカチカしてるのが目に悪い

**Comment by TinyKitten** [comment]
- スクショ防止でもQR出てる画面で下の方がチカチカしてるのが目に悪い
- 背景の幾何学？みたいな模様が目移りして邪魔
