### ISSUE TITLE
Stripe Webhooks調査

### ISSUE THREAD

**Issue by 10mocy** [sockbase/Sockbase#25]
Related #8 

https://developer.squareup.com/docs/webhooks/overview

**Comment by 10mocy** [comment]
今回の決済フローとして、

1. Stripeが提供する決済画面からクレジットカード情報等を入力して決済
2. 決済が完了されたことをWebhooksでSockbaseシステムに通知
3. Sockbaseシステムでそれを受け取り、決済管理情報を更新

を行う予定なので、それが実現できそうか調査してもらいたいです。
個人的には1が提供されてるのかが疑問(提供されてない場合はSockbase側で作らないと行けなさそう)

**Comment by youku-s** [comment]
- 購読するWebhookはおそらく `payment.created`
- このEvent Objectから `order_id` を取得する
- `GET /v2/orders/{order_id}` から、`catalog_object_id` を取得する
- `GET /v2/catalog/object/{object_id}`から、CatalogObjectを取得する
  - typeが `ITEM` の場合は、多分一般参加者のチケットになる。`id` をユニークな商品のIDとして取得する
  - typeが `ITEM_VARIATION` の場合は、多分サークル参加者の決済になる(スペース数などのバリエーションが存在するので)。`id` をユニークな商品のIDとして取得する

**Comment by youku-s** [comment]
参考
https://developer.squareup.com/reference/square/orders-api/retrieve-order
https://developer.squareup.com/reference/square/catalog-api/retrieve-catalog-object
https://developer.squareup.com/docs/catalog-api/what-it-does
https://developer.squareup.com/reference/square/webhooks/payment.created

**Comment by youku-s** [comment]
> 今回の決済フローとして、
> 
> 1. Squareが提供する決済画面からクレジットカード情報等を入力して決済
> 2. 決済が完了されたことをWebhooksでSockbaseシステムに通知
> 3. Sockbaseシステムでそれを受け取り、決済管理情報を更新
>    を行う予定なので、それが実現できそうか調査してもらいたいです。
>    個人的には1が提供されてるのかが疑問(提供されてない場合はSockbase側で作らないといけなさそう)

これをStripeに置き換えた話について、調査していきます。

**Comment by youku-s** [comment]
> Squareが提供する決済画面からクレジットカード情報等を入力して決済
Stripe Checkoutがそれに該当する。
https://stripe.com/jp/payments/checkout

**Comment by youku-s** [comment]
> 決済が完了されたことをWebhooksでSockbaseシステムに通知

Webhook登録方法は以下。
https://stripe.com/docs/development/dashboard/register-webhook?locale=ja-JP

購読するイベントは以下3つ。
説明：https://stripe.com/docs/payments/checkout/fulfill-orders?locale=ja-JP#delayed-notification

-  `checkout.session.completed`
-  `checkout.session.async_payment_succeeded`
-  `checkout.session.async_payment_failed`

Webhookで取得できるオブジェクトの形式に関しては、以下。
https://stripe.com/docs/api/events/object
https://stripe.com/docs/api/checkout/sessions/object

- 一連の流れ
  - https://stripe.com/docs/payments/checkout/fulfill-orders?locale=ja-JP#delayed-notification
    - Checkuoutを使用する場合は、payment_intentを直接購読しないので注意
    - 即決済・遅延決済の両パターンを考慮する必要あり。基本的にはサンプルコードの流れに従えばOK

**Comment by youku-s** [comment]
@10mocy 一通り調べ終わりましたので、報告します。
結論から言うと、Stripe CheckoutでStripeホスティングの決済フロントエンドを作成可能。それの決済をトリガーにWebhookでSockbaseに通知するフローの構築も可能です。
詳細は前述のコメントを参照のこと。

このまま私に決済まわりのタスクを任せるのであれば、後続タスクの用意、およびStripe(+Stripe Checkout)アカウントの用意をお願いいたします。

**Comment by 10mocy** [comment]
調査ありがとうございます。
確認しました！
それではstripeで進めます、アカウント等は少々お待ちください！

**Comment by 10mocy** [comment]
Related #38
