### ISSUE TITLE
Stripe決済実装

### ISSUE THREAD

**Issue by 10mocy** [sockbase/Sockbase#38]
以下の機能の実装をお願いします。

- Cloud Functions関数
  - [ ] 決済管理データ作成関数
  - [ ] 決済管理ステータス更新用関数
  - [ ] 決済管理ステータス更新

決済管理データは以下の仕様でお願いします。

パス: `/_payments/:autoGeneratedId`

- `userId`: string ユーザID(Firebaseのuid)
- `paymentProductId`: string Stripe商品ID
- `paymentType`: enum 支払方法(1: online(オンライン決済), 2: bankTransfer(銀行振込))
- `paymentId`: string? Stripe支払い連携用ID(オンライン決済の場合のみ。この時bankTransferCodeはundefined)
- `bankTransferCode`: string? 銀行振込紐付け用コード(銀行振込の場合のみ。この場合paymentIdはundefined)
- `paymentAmount`: number 支払い額
- `status`: enum 決済ステータス(0: pending(未払い), 1: paid(支払済), 2: refunded(返金済))
- `applicationId`: string? 紐づける申込みId(サークル申し込みの場合。この時ticketIdはundefined)
- `ticketId`: string? 紐づけるチケットId(チケット申し込みの場合。この時applicationIdはundefined)
- `createdAt`: timestamp Firebaseサーバ タイムスタンプ
- `updatedAt`: timestamp Firebaseサーバ タイムスタンプ

enumの実装参考: https://github.com/sockbase/Sockbase/blob/feature/%2335.Dashboard.ApplicationStatus/packages/shared/src/enumerations.ts

## 銀行振込時のID

銀行振込の場合、振込名義用に6桁ぐらいの数字で構成されたIDを生成して付番したい
日日時時分分フォーマット

例 1月2日 15:04に生成したデータなら 021504
例 5月16日 19:08なら 161908
例 A月BB日 CC:DDなら BBCCDD

このIDを振り込み名義の先頭につけてもらう
021504ソメミヤネイロ
161908コハルリッカ
みたいな感じ

**Comment by 10mocy** [comment]
最新の機能を `feature/#7.Dashboard.CircleApplication` に取り込んでいるので、必要に応じて取り込んでください。

**Comment by youku-s** [comment]
@10mocy 
> 決済管理データ作成関数
> 決済管理ステータス更新用関数
> 決済管理ステータス更新

この機能で何をするのかが良くわからなかったです。
こちらの認識としては、CheckoutのWebhookの3つのイベントを処理する1つのCloudFunctionがあればいい認識です。
- `checkout.session.completed`：即支払いが完了したか、カードによる遅延払いが予定されたタイミングで発行されるイベント
  - 即支払いが完了した場合は、`_payments` オブジェクトを作成し、決済のステータスを支払い済みにする
  - 遅延払いの場合は、`_payments` オブジェクトを作成し、決済のステータスを未払いに設定する
- `checkout.session.async_payment_succeeded`：遅延払いが正常処理されたタイミングで発行されるイベント
  - `_payments` オブジェクトを更新し、決済のステータスを支払い済みに設定する
- `checkout.session.async_payment_failed`：遅延払いが失敗したタイミングで発行されるイベント
  - `_payments` オブジェクトを更新し、決済のステータスを支払い失敗に設定する

**Comment by 10mocy** [comment]
ご提示いただいた内容を処理する実装があれば問題ありません！

**Comment by youku-s** [comment]
@10mocy 
了解です。明日実装します！

**Comment by youku-s** [comment]
@10mocy 
> userId: string ユーザID(Firebaseのuid)
> paymentId: string? Stripe支払い連携用ID(オンライン決済の場合のみ。この時bankTransferCodeはundefined)
> bankTransferCode: string? 銀行振込紐付け用コード(銀行振込の場合のみ。この場合paymentIdはundefined)
> applicationId: string? 紐づける申込みId(サークル申し込みの場合。この時ticketIdはundefined)
> ticketId: string? 紐づけるチケットId(チケット申し込みの場合。この時applicationIdはundefined)

こちら、取得方法はどこからですか？
ちょっとわからなかったです。

> status: enum 決済ステータス(0: pending(未払い), 1: paid(支払済), 2: refunded(返金済))

支払いが失敗したけどまだ返金が済んでいないステータス(3: payment_failure)を追加したいです。

**Comment by youku-s** [comment]
@10mocy 
- 決済管理データ？
    - その場で採番しちゃってよい、ということであっていますか？
    - paymentId、bankTransferCode、bankTransferCode、ticketIdに関してはその場採番でいいとしても、userIdはそういうわけにはいかない気がします
 - 判別について
    - 了解です！

**Comment by 10mocy** [comment]
@youku-s 
- userId: firebaseのUIDなのでリクエスト時に取れます
- paymentId: stripeの決済を特定できる一意のID
- bankTransferCode: 銀行振込時に特定するためのコード(生成方法はissue概要に記載しています)
- applicationId: サークル申込情報の格納先のID
- ticketId: チケット情報の格納先のID

**Comment by youku-s** [comment]
@10mocy 
> userId: firebaseのUIDなのでリクエスト時に取れます

stripeにkickされるWebhookなので、リクエストから取れるUIDは振り込みを行ったユーザーのIDにはならないのでは？

**Comment by 10mocy** [comment]
@youku-s フローとしては以下のようになる
想定なのですが、いかがでしょうか？

- サークル, チケット申込時
  - 決済管理データを作成。
  - bankTransferCodeとかはここで生成。
- stripe webhooksトリガー時
  - ユーザID: メアドで検索引っ掛けないと特定出来なさそう……と思いました。
    - メールアドレスを保管するコレクションを作って解決できる。

**Comment by youku-s** [comment]
@10mocy 
`_payments`ですが、サークル, チケット申込時に商品idを設定してもらうことはできますか？
これがないと、同一ユーザーに複数決済が存在する場合に、どの決済管理データのレコードを更新するかが決定できないので。
サービス設計上1ユーザーに対して決済が1つしか存在しないなら、このままでいいです。

**Comment by 10mocy** [comment]
@youku-s 了解です。各申込時にpaymentProductIdというプロパティに商品コードを入れるようにしておけば問題なさそうでしょうか？(Webhooksトリガー時は、paymentProductIdとstatus=pendingを１つ取ってくれば更新できるかな。UX的にも問題なさそう)

**Comment by youku-s** [comment]
@10mocy それで問題ないです！

**Comment by 10mocy** [comment]
@youku-s 了解しました。一旦定義だけ上げておきます。

**Comment by youku-s** [comment]
@10mocy PR見ました。
SockbaseApplication にpaymentProductIdが追加されているのを確認しました。

ただ、SockbaseApplicationはどうやって検索したらよいですか？
ログイン情報 or emailからSockbaseApplicationを引き当てる方法がなさそうに見えます。(nameであてるのは同姓同名がありうるので筋が悪いはず)
あと、SockbaseApplicationってチケット申込の場合も作成されるという認識であっていますか？

**Comment by 10mocy** [comment]
@youku-s 

1. トリガー時は `メールアドレス` が分かっている
2. ユーザ情報コレクションから `メールアドレス` でユーザ情報を引っ張ってくる(`UserId` が判明する)
3. `UserId` と `トリガー時のStripe商品コード` で決済データ自体は取ってこれそう

- 決済管理データに商品コードあったほうが良いですよね…、何でSockbaseApplicationに突っ込んだんだろ…
- SockbasePaymentDocumentというインタフェースを作って、そこでPaymentProductId管理するようにしましょうか。

**Comment by 10mocy** [comment]
@youku-s PaymentProductIdをSockbaseApplicationの定義を外すので、決済管理データに同じ型で追加していただいてもよろしいでしょうか？
